### ISSUE TITLE
Documentation format 

### ISSUE THREAD

**Issue by thim81** [reddec/monexec#12]
Hi Aleksandr,

It looks like the documentation is a bit messed with the markdown formatting.
Not really critical, but I thought I mentioned it.

There is some confusion on the parameters because of the samples:
`graceful-timeout:5s` vs `stop_timeout: 5s`

Regards,
Tim

**Comment by thim81** [comment]
Additional I'm confused on the `args`
Is it required to pass command arguments in the "args" section of the yml file or is possible to pass with the command?

As arguments:
```
services:
- label: node
  command: node app.js
  logFile: /var/log/node.log
  args:
  - -p 3000
  graceful-timeout: 5s # Timeout for graceful shutdown.
  workdir: /opt/approot/current # Workdir for the command executable
  restart_delay: 5s # Delay before restart
  restart: -1 # Restart count (negative means infinity)
rest:  
 listen: "1270.0.01:9900" 
 cors: false
```

or with the command:
```
services:
- label: node
  command: node app.js -p 3000
  logFile: /var/log/node.log
  graceful-timeout: 5s # Timeout for graceful shutdown.
  workdir: /opt/approot/current # Workdir for the command executable
  restart_delay: 5s # Delay before restart
  restart: -1 # Restart count (negative means infinity)
rest:  
 listen: "1270.0.01:9900" 
 cors: false
```

**Comment by reddec** [comment]
Hi @thim81 ! Thanks for you question. Let me answer in a reverse order:

### args

In your example both way is not ideal: all arguments should be separated.
```yaml
services:
- label: node
  command: node app.js
  logFile: /var/log/node.log
  args:
  - -p 
  - "3000"
  graceful-timeout: 5s # Timeout for graceful shutdown.
  workdir: /opt/approot/current # Workdir for the command executable
  restart_delay: 5s # Delay before restart
  restart: -1 # Restart count (negative means infinity)
rest:  
 listen: "1270.0.01:9900" 
 cors: false
```

And yes, it should be separated. There is a way how to start single command, however I personally dislike it due to security issue: when all arguments are passing separately, it's impossible to make an insecure call.

Let me show a some theoretical example: assume that `command` accepts a single-line command that should be invoked by the system. In some cases (not only by hackers, but just by mistake) someone may write command like: `echo aa bb cc; ls /`. That will interpreted by the shell as a two commands: `echo aa bb cc` and `ls /` that probably not what you really want to do.

In case of separated arguments, all arguments passed not to shell but to the command it self. So it doesn't matter what symbols, escaping characters or anything else someone will put.

Anyway there is still a hack: to set `command: /usr/bin/bash`  and `args: ['-c', 'any complex command'].

However, writing manually all parameters can make a hassle. To help with it, monexec has a special CLI argument: `--generate` that will make most parameters automatically. For example:
`monexec run --generate -- nc -l 9001` creates:
```yaml
services:
- label: crystal-spangle
  command: nc
  args:
  - -l
  - "9001"
  stop_timeout: 5s
  restart_delay: 5s
  restart: -1
```

### timeouts

`graceful-timeout` it's a CLI command that maps to `stop_timeout` in YAML config.

Please, let me know if you have any more questions

**Comment by thim81** [comment]
hi @reddec 

Thanks for a very good and clear explanation.

It would be helpful if you could list all yaml config options, and their defaults, in the documentation:
This is what I found, but please complete or correct.

Full example of a YAML config with .ENV file
```
services:
- label: crystal-spangle
  command: nc
  args:
  - -l
  - "9001"
  stop_timeout: 5s
  restart_delay: 5s
  restart: -1
  logFile: /var/log/crystal-spangle.log
  workdir: /opt/approot/current
  envFile: .env Q: will this file be looked up in the workdir? or does it have to be an absolute path?
```

Full example of a YAML config with environment
```
services:
- label: crystal-spangle
  command: nc
  args:
  - -l
  - "9001"
  stop_timeout: 5s
  restart_delay: 5s
  restart: -1
  logFile: /var/log/crystal-spangle.log
  workdir: /opt/approot/current
  environment: ???  
```


YAML options:
_services_ Section to define the list of services/commands
**label** Label name for executable/service. Default - autogenerated
**command** path/to/executable
**args**  a list of command argument, all arguments should start with `-` 
**stop_timeout** Timeout for graceful shutdown. Application first got signal SIGTERM and after this timeout SIGKIL. Default is 5s?
**restart-delay** Delay before restart.Default is 5s?
**restart** Restart count (negative means infinity)
**logFile** The location where all the output of the command is captured. Q: Will this create the log folder or should it exist? 
**workdir** Workdir for executable, the location where the command will be executed.
**environment** Q: is this a list of comma seperated key values?

Full example of a YAML config with Consul
```
services:
- label: crystal-spangle
  command: nc
  args:
  - -l
  - "9001"
  stop_timeout: 5s
  restart_delay: 5s
  restart: -1
  logFile: /var/log/crystal-spangle.log
  workdir: /opt/approot/current
consul:
  url: http://localhost:8500
  ttl: 3s
  timeout: 1m0s
  permanent:
  - crystal-spangle
```
_consul_ Section to define the consul settings
**url** address of the consul service
**ttl** Keep-alive TTL for services
**timeout** Timeout after for auto de-registration: 1m0s
_permanent_ Keep service in consul auto timeout
**listener** Name of the listener service to keep the service in auto timeout

Another question: The `--generate` option, will this create the file and then use it via "monexec start" or does it only create the file? Thinking about the use case of CI/CD integration, where usually based on parameters code is deployed and the process (monexec) will be run/started. 

How would you integrate it in a CI/CD flow?
build app ...
1) monexec run --generate in CI/CD task
2) stop monexec in CI/CD task
3) monoexec start *.yml in CI/CD task

My idea was to use the "command" as parameter in the CI/CD flow, which would result in yml file, which would used in the CI/CD flow to (re)start the monexec.
build app ...
1) Generate yaml file using bash in CI/CD task
2) monoexec start *.yml in CI/CD task

Just thinking about automation, would love to hear you experience on this.
